-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS maps CASCADE;
DROP TABLE IF EXISTS pins CASCADE;
DROP TABLE IF EXISTS layers CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) DELETE ON CASCADE,
  thumbnail_image VARCHAR(255) NOT NULL,
  longitude REAL,
  latitude REAL
);

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) DELETE ON CASCADE,
  map_id INTEGER REFERENCES map(id) DELETE ON CASCADE
);

CREATE TABLE layers (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  user INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE
);

CREATE TABLE pins (
  id SERIAL PRIMARY KEY NOT NULL,
  contributor_id INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
  map_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnail_image VARCHAR(255) NOT NULL,
  longitude REAL,
  latitude REAL,
  layer_id INTEGER NOT NULL REFERENCES layers(id) ON DELETE CASCADE
);


